### ISSUE TITLE
Solution Import Error

### ISSUE THREAD

**Issue by cassirk** [OfficeDev/microsoft-teams-apps-inspection#3]
The provided source code appears to be from a previous version of Microsoft Dynamics 365 and will not import.
Error message from Power Apps:
![image](https://user-images.githubusercontent.com/46687676/111193206-8abe4c00-857f-11eb-93e0-3fed4056c560.png)

This is not the same issues as #1 .  All the correct files seem to be in the root at this point.

**Comment by schneika** [comment]
The same here. Can not Import the provided Solution file. Wrong Root-Folder, should not be a sub-Folder!
You should repack the Package in a new Solution.zip with the right Root-Folder, not as sub-Folder. Than you can import the solution

**Comment by schneika** [comment]
Please see here the correct Root-Folder-Structure
![image](https://user-images.githubusercontent.com/11440416/112147224-bcb55b00-8bdc-11eb-849a-2bdd0bf4fcc9.png)

**Comment by cassirk** [comment]
> Please see here the correct Root-Folder-Structure
> ![image](https://user-images.githubusercontent.com/11440416/112147224-bcb55b00-8bdc-11eb-849a-2bdd0bf4fcc9.png)

This fixed my issue.  Thanks @schneika!
